### ISSUE TITLE
Declaració i allocate de pos(D,N) i vel(D,N)

### ISSUE THREAD

**Issue by EloiSanchez** [EIA-Master/Project_2021_I#10]
- Hem de triar on declarem aquests dos arrays. Si ho fem al main haurem de passar-los a les subrutines, si ho fem en un modul (afegir-los al parameters o fer-ne un de nou) nomes caldra fer el use, però potser queda menys clar el que esta passant des del main.

- També hem de fer els allocates i deallocates, de nou podem triar main o una subrutina a part.

**Comment by arnau-jr** [comment]
Quedarà més clar declarant i fent els allocates i deallocates al main, si afegim pos i vel a parametres el 90% dels calls seran sense arguments i aixo fa que no quedi massa clar que se està modificant a cada subrutina.
Si estem d'acord tanco issue.´

**Comment by EloiSanchez** [comment]
També crec que serà mes clar així. Per mi tanquem el issue i ho deixem com ho tenim ara.
