### ISSUE TITLE
Random seeds

### ISSUE THREAD

**Issue by EloiSanchez** [EIA-Master/Project_2021_I#103]
Pregunta sobre les seeds. Fem una inicialització única on cada tasca te una seed durant tot el programa o cadascú inicialitza la seed en cada tasca com ell vulgui?
Ara al init_vel jo he fet una seed per cada tasca pero es una variable local de la subrutina.

**Comment by arnau-jr** [comment]
Per fer-ho consistent potser seria millor que la seed fos un input i al main que es fes la inicialització. Per cada tasca podem fer simplement la inpu_seed+taskid (master agafar l'input, com si fos un programa en serie i la resta agafaran altres seeds).

**Comment by EloiSanchez** [comment]
D'acord, fet :)
