### ISSUE TITLE
Diferents dt per diferents simulacions.

### ISSUE THREAD

**Issue by arnau-jr** [EIA-Master/Project_2021_I#18]
Ara mateix tenim un únic pas de temps introduït per l'usuari pero a la fase de melting necessitariem un dt més petit ja que posem una temperatura alta que requereix de major definició.

Ara mateix les subrutines verlet (Laia) estan fetes per a que acceptin qualsevol dt com a argument pero aquest es el mateix nom que utilitzem a parametres, així que pot crear problemes. Proposo canviar la dt de parametres a dt_sim o dt_set o algo per l'estil per diferenciar entre la dt de la simulació principal i la dt que utilitzem per altres coses (com el melting).

**Comment by EloiSanchez** [comment]
Aleshores seria cridar el melting amb un dt fixat (igual que es crida el init_vel amb una T inicial fixada) i que el dt de la subrutina de la Laia es llegeixi directament desde el _use parameters_. Potser no cal crear una nova variable si no la modificarem en altres inputs (és a dir, sempre farem el melting a una T' reduida i un dt fixes no donats al input).

**Comment by arnau-jr** [comment]
Sempre cridariem les subrutines de la Laia amb el dt que toqui per no causar confusions, el que vull dir es que internament la Laia utilitza dt (que es el mateix nom que a parameters) aixi que potser hi ha problemes. Si canvie el nom a parameters a dt_sim (per exemple) i cridem com call vvel_solver(...dt_sim...) segur que no ens equivoquem.

**Comment by EloiSanchez** [comment]
Vale, llavors canviem el dt de l'input i de parameters. Ara ho faig.

**Comment by arnau-jr** [comment]
Tens rao, arreglo la sigma de l'Andersen, tanco issue.
