### ISSUE TITLE
rand() intrínsic suficient per termostat?

### ISSUE THREAD

**Issue by arnau-jr** [EIA-Master/Project_2021_I#19]
A MoMo utilitzavem el RNG intrinsíc de fortran per el termostat d'Andersen, pero m'he adonat que en realitat es generen bastant números aleatoris fent servir el termóstat (de l'ordre de 7N per pas de temps ja que no aprofito el Box Muller completament). Això no arriba al número de números que es generen a un MC (principlament perque no es fan tants passos de temps) però segueixen sent bastants. Valdria la pena invertir en un millor RNG?´

**Comment by dmarchp** [comment]
Jo crec que es podria fer servir el mersenne twister, no canvia massa el programa, seria afegir un fitxer amb el modul i posar el use mtmod a les subrutines que fagi falta, més inicialitzar-lo al programa principal.
En termes de velocitat no sé si afecta massa per això.

**Comment by a96lex** [comment]
Està resolt això?

**Comment by arnau-jr** [comment]
De moment tanco la issue, a MoMo no ens va causar problemes i no crec que aqui ens el vagi a causar.
