### ISSUE TITLE
Directori ./results/ no es crea automàticament

### ISSUE THREAD

**Issue by EloiSanchez** [EIA-Master/Project_2021_I#45]
He clonat el repositori en una altra màquina, i com que vam eliminar la carpeta ./results/ fortran dona un Runtime error. En l'ordinador anterior, com que vam crear la carpeta results des del principi, no se m'ha esborrat i no tenia aquest problema.

Per reproduir:
1) Clonar el repositori en un directori nou ```>> git clone https://github.com/EIA-Master/Project_2021_I```, ja sigui aquest o la fork pròpia de cadascú.
2) Compilar amb ```>> make```
3) Executar amb ```>> ./main.x input_template.txt``` em produeix ```Fortran runtime error: Cannot open file 'results/thermodynamics_initialization.dat': No such file or directory```

He comprovat que al crear el directori ./results/ deixa de apareixer el problema. Caldria fer que el Makefile o el propi codi creïn aquest directori si no hi és. Podriem aprofitar a l'arreglar això per afegir l'execució de tots els inputs a la vegada i cada un generi els seus outputs per fer els plots i demés automàticament amb una comanda tipus ```make all``` o algo així.

**Comment by arnau-jr** [comment]
S'hauria d'afegir una norma al make o crear el directori desde el codi de fortran.

**Comment by a96lex** [comment]
desde fortarn es pot fer call execute_command_line("mkdir -p results")
desde makefile es pot fer posant mkdir -p results a qualsevol lloc. Jo prefereixo a fortran

Per altra banda, make clean neteja intermitjos de compilació. 
Si volem eliminar resultats (no ho veig necessari) cal un altra recepta (make removeResults o algo)

**Comment by EloiSanchez** [comment]
Afegeixo tant el ```mkdir -p results``` al Makefile com la nova norma per netejar-ho tot amb ```make clean_all``` i faig pull.
