### ISSUE TITLE
Versionat de resultats

### ISSUE THREAD

**Issue by a96lex** [EIA-Master/Project_2021_I#46]
Imaginem que l'usuari sense voler torna a executar main.x sense haver guardat els resultats anteriors. Volem prevenir això?

Se m'acudeix que, abans de obrir tots els documents a fortran, podem afegir una peça de codi que faci una de les següents funcions:
- si hi ha resultats a la carpeta de resultats, els agafa tots i els copia a un nou directori que s'anomeni /results/(string amb el dia i hora actuals) 
- si hi ha resultats a la carpeta de resultats que crei /results/versio_{n} on {n} és el valor máxim que trobi en les carpetes que s'anomenin /versio_{n} en el directori de resultats més 1

L'altra opció és directament anomenar la carpeta com a /results/version_1 o /results/hora_actual. Si és així, s'ha de modificar python i fortran, ja que directament van a results

**Comment by a96lex** [comment]
Vale, el més fàcil és una recepta de makefile que agafi la carmeta resultats i li canvii el nom a /resltats-temps_actual.

Faix un pr amb aquesta última idea, si volem canviar-ho ho canvio, cap problema

**Comment by arnau-jr** [comment]
Jo tambe crec que temps actual es mes facil, rapid i menys lios. Si fem l'altra sistema i hi ha versio 1,2 i 3 i l'usuari esborra 2 i torna a correr el nou 2 es mes modern que 3 i es una mica embolicat (tot i que linux si que s'enrecordaria de qui es mes antic).

**Comment by a96lex** [comment]
#48 arreglat aquí

**Comment by arnau-jr** [comment]
Perfecte, tanco issue.
