### ISSUE TITLE
Comportament extrany en l'arxiu de distribució radial

### ISSUE THREAD

**Issue by a96lex** [EIA-Master/Project_2021_I#55]
Interessantment, si a gnuplot faig plot `"./results/radial_distribution.dat" u 1:2` surt una linea recta

La funció es representa correctament si ho faug utilitzant 1:3 en comptes de 1:2.

Podem o bé no tocar-ho i resar que sempre surti bé o investigar si és problema del format de les dades, però aparentment estan bé.

**Comment by a96lex** [comment]
amb 1:2
![image](https://user-images.githubusercontent.com/62766970/109851750-54fe9680-7c54-11eb-87f5-187cbf52b51d.png)

amb 1:3
![image](https://user-images.githubusercontent.com/62766970/109851815-65167600-7c54-11eb-90fe-60bf42d67b8b.png)

**Comment by arnau-jr** [comment]
No es un extrany, si mires l'arxiu de la g(r) la primera columna es la r en unitats reduides, la segona en angstroms i la tercera la g(r). Si representes 1:2 estas fent una recta on el pendent es la sigma (unitat de longitud reduida).

**Comment by a96lex** [comment]
Ho acabo de veure. Estaba mirant un arxiu de dades que vaig fer ahir :confused:
