### ISSUE TITLE
Possible millora: afegir un n_equil

### ISSUE THREAD

**Issue by arnau-jr** [EIA-Master/Project_2021_I#62]
Ara mateix despres de fer la inicialitzacio anem directament a la simulacio principal, mirant les grafiques es pot veure que el sistema no esta a l'equilibri al principi i que s'haurian de deixar unes 1000-2000 iteracions mes (o mes en funcio del dt) per a que el sistema entri en equilbri.
![Temperatura](https://user-images.githubusercontent.com/48213666/109939015-ee6b8e00-7cd0-11eb-8912-e9c4810ab93f.png)

A la temperatura es veu clarament, la T_ref era de 2.00 en aquesta simulacio (tambe pot ser culpa de que el termostat no es suficientment rapid).

**Comment by EloiSanchez** [comment]
Aquest problema el tindrem (en major o menor mesura) independentment de la força d'acoblament del termostat. Crec que el millor es fer el que comentes i afegir unes iteracions per arribar a l'equilibri. Podem afegir-ho com a variable d'input o fixar-ho al propi codi. Jo crec que el millor seria deixar la variable a l'input i que es pugui modificar per l'usuari.

**Comment by arnau-jr** [comment]
Si, millor variable com a input ja que dependra del deltat.

**Comment by EloiSanchez** [comment]
Fet.

**Comment by arnau-jr** [comment]
Genial, tanco issue.
